// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZyCz9oXvTbawC1bv7Qqpp8L_7pHP4TV0',
    appId: '1:811967007667:web:9588dea4c266c7af7c19c6',
    messagingSenderId: '811967007667',
    projectId: 'chat-app-c989e',
    authDomain: 'chat-app-c989e.firebaseapp.com',
    databaseURL: 'https://chat-app-c989e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c989e.appspot.com',
    measurementId: 'G-KKFRM9RXEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSqKtIxH6o3uoxuu1a72WmQ1Tg96MSC0c',
    appId: '1:811967007667:android:4e173cf4932960e37c19c6',
    messagingSenderId: '811967007667',
    projectId: 'chat-app-c989e',
    databaseURL: 'https://chat-app-c989e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c989e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE-MwEBXmDxvkCCEHjIKp86WvXeYDZPqY',
    appId: '1:811967007667:ios:40607c9cb295ff697c19c6',
    messagingSenderId: '811967007667',
    projectId: 'chat-app-c989e',
    databaseURL: 'https://chat-app-c989e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c989e.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE-MwEBXmDxvkCCEHjIKp86WvXeYDZPqY',
    appId: '1:811967007667:ios:40607c9cb295ff697c19c6',
    messagingSenderId: '811967007667',
    projectId: 'chat-app-c989e',
    databaseURL: 'https://chat-app-c989e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c989e.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZyCz9oXvTbawC1bv7Qqpp8L_7pHP4TV0',
    appId: '1:811967007667:web:dec39ce1b9fa181f7c19c6',
    messagingSenderId: '811967007667',
    projectId: 'chat-app-c989e',
    authDomain: 'chat-app-c989e.firebaseapp.com',
    databaseURL: 'https://chat-app-c989e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c989e.appspot.com',
    measurementId: 'G-SKPWRRGT68',
  );
}
